"""Add user logo_url

Revision ID: 1aa0a0274e02
Revises: 67bf4ee7ddde
Create Date: 2026-04-19 03:46:28.349517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aa0a0274e02'
down_revision = '67bf4ee7ddde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('logo_url')

    # ### end Alembic commands ###
