"""add phone column

Revision ID: 51e6135ee749
Revises: 6c17854b3b2f
Create Date: 2026-04-23 07:19:17.906106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51e6135ee749'
down_revision = '6c17854b3b2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
