"""add plan_expires_at to user

Revision ID: 6c17854b3b2f
Revises: d979457d89f2
Create Date: 2026-04-21 12:12:05.194752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c17854b3b2f'
down_revision = 'd979457d89f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('plan_expires_at')

    # ### end Alembic commands ###
