"""Add user gst_number

Revision ID: d979457d89f2
Revises: 2f3b2f7d7bc1
Create Date: 2026-04-20 06:57:27.207179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd979457d89f2'
down_revision = '2f3b2f7d7bc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gst_number', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('gst_number')

    # ### end Alembic commands ###
